const venues = [
  {
    slug: "the-rusty-string",
    name: "The Rusty String",
    emoji: "🎸",
    genre: "Indie / Folk",
    neighborhood: "East Side",
    address: "412 Magnolia Ave",
    shortDesc: "A cozy dive bar famous for intimate acoustic sets and open mics every Tuesday.",
    fullDesc: "The Rusty String has been a beloved East Side institution since 1998. With mismatched furniture, exposed brick walls, and a stage barely big enough for a trio, it's the kind of place where you might accidentally discover your new favorite artist. Their Tuesday open mic nights have launched several regional touring acts, and the Wednesday songwriter-in-the-round nights attract serious music fans from across the city.",
    coverCharge: 0,
    ageRestriction: "21+",
    capacity: 80,
    hours: "Tue–Sun 5pm–2am",
    bestNight: "Tuesday (Open Mic)",
    vibe: "Intimate & Unpretentious",
    upcomingShows: [
      { date: "Tue Jun 10", artist: "Open Mic Night", price: 0 },
      { date: "Fri Jun 13", artist: "Maya Reyes Trio", price: 8 },
      { date: "Sat Jun 14", artist: "Hollow Creek", price: 10 },
      { date: "Thu Jun 19", artist: "Songwriter Round", price: 0 },
    ],
  },
  {
    slug: "neon-cathedral",
    name: "Neon Cathedral",
    emoji: "🔊",
    genre: "Electronic / DJ",
    neighborhood: "Downtown",
    address: "88 West Commerce St",
    shortDesc: "Atlanta's premier underground electronic venue with a legendary sound system.",
    fullDesc: "Neon Cathedral opened in 2017 inside a converted warehouse and quickly became the city's go-to spot for serious electronic music. The sound system — custom-built by a Berlin-based engineer — delivers bass you feel in your chest from anywhere on the dance floor. The venue books a mix of internationally touring DJs and local talent, with a strict no-phones policy during headliner sets to keep the energy pure.",
    coverCharge: 15,
    ageRestriction: "18+",
    capacity: 400,
    hours: "Fri–Sat 9pm–4am",
    bestNight: "Saturday",
    vibe: "High Energy / Immersive",
    upcomingShows: [
      { date: "Fri Jun 13", artist: "DJ Solaris", price: 15 },
      { date: "Sat Jun 14", artist: "Vex & Luma (Berlin)", price: 20 },
      { date: "Fri Jun 20", artist: "Local Selectors Night", price: 10 },
      { date: "Sat Jun 21", artist: "Nocturne B2B Ghost Freq", price: 18 },
    ],
  },
  {
    slug: "blue-note-lounge",
    name: "Blue Note Lounge",
    emoji: "🎷",
    genre: "Jazz / Blues",
    neighborhood: "Midtown",
    address: "219 Peachtree Terrace",
    shortDesc: "Old-school jazz lounge with nightly live bands and the best old fashioned in town.",
    fullDesc: "Opened in 1962 and still owned by the same family, Blue Note Lounge is a living piece of the city's musical history. The red velvet booths, candlelit tables, and a bar stocked with rare whiskeys set the mood before the first note is even played. The house band performs Wednesday through Sunday, and on Monday nights the venue hosts a legendary jazz jam that attracts working musicians from across the Southeast.",
    coverCharge: 5,
    ageRestriction: "21+",
    capacity: 120,
    hours: "Mon–Sun 6pm–1am",
    bestNight: "Monday (Jazz Jam)",
    vibe: "Classic & Sophisticated",
    upcomingShows: [
      { date: "Mon Jun 9", artist: "Monday Jazz Jam", price: 0 },
      { date: "Wed Jun 11", artist: "The House Quartet", price: 5 },
      { date: "Sat Jun 14", artist: "Veronica Salas & Band", price: 12 },
      { date: "Sun Jun 15", artist: "Sunday Blues Session", price: 5 },
    ],
  },
  {
    slug: "the-pit",
    name: "The Pit",
    emoji: "🤘",
    genre: "Punk / Metal / Hardcore",
    neighborhood: "Little Five Points",
    address: "56 Euclid Ave NE",
    shortDesc: "No-frills punk venue where local hardcore acts and touring bands pack em in.",
    fullDesc: "The Pit is exactly what it sounds like — a raw, loud, sweat-soaked room where the music hits hard and nobody's pretending otherwise. The stage is about two feet off the ground, the PA is cranked, and the crowd knows every word to every song. For over a decade, it's been the launching pad for the city's punk and hardcore scene. If you want polished production, this is not your spot. If you want real, The Pit delivers.",
    coverCharge: 10,
    ageRestriction: "All Ages",
    capacity: 200,
    hours: "Thu–Sun 7pm–midnight",
    bestNight: "Friday",
    vibe: "Raw & Loud",
    upcomingShows: [
      { date: "Thu Jun 12", artist: "Void Margin + Locals", price: 8 },
      { date: "Fri Jun 13", artist: "Concrete Heist (touring)", price: 12 },
      { date: "Sat Jun 14", artist: "All-Ages Showcase", price: 10 },
      { date: "Sun Jun 15", artist: "Sunday Matinee", price: 5 },
    ],
  },
  {
    slug: "rooftop-sessions",
    name: "Rooftop Sessions",
    emoji: "🌆",
    genre: "R&B / Hip-Hop / Soul",
    neighborhood: "West Midtown",
    address: "730 Howell Mill Rd (Rooftop)",
    shortDesc: "Open-air rooftop venue with skyline views and a rotating roster of R&B and hip-hop acts.",
    fullDesc: "There is no better way to spend a summer evening than on the rooftop of this former industrial building, watching the city skyline light up while a live band grooves into the night. Rooftop Sessions books local R&B vocalists, neo-soul artists, and hip-hop performers, with the occasional national touring act. The venue also hosts a monthly beat-making showcase where local producers perform their original instrumentals live.",
    coverCharge: 12,
    ageRestriction: "21+",
    capacity: 250,
    hours: "Thu–Sat 6pm–midnight",
    bestNight: "Saturday",
    vibe: "Vibey & Scenic",
    upcomingShows: [
      { date: "Thu Jun 12", artist: "Velvet Frequency", price: 10 },
      { date: "Fri Jun 13", artist: "Deja Soul Collective", price: 12 },
      { date: "Sat Jun 14", artist: "Marcus Webb Live Band", price: 15 },
      { date: "Sat Jun 21", artist: "Beat Showcase Vol. 8", price: 10 },
    ],
  },
  {
    slug: "vinyl-chapel",
    name: "Vinyl Chapel",
    emoji: "🎹",
    genre: "Indie / Experimental",
    neighborhood: "Poncey-Highland",
    address: "1104 N Highland Ave",
    shortDesc: "Converted chapel turned listening room — where experimental and indie acts get the reverence they deserve.",
    fullDesc: "Inside a lovingly restored 1920s chapel, Vinyl Chapel has created one of the city's most acoustically stunning performance spaces. The vaulted ceilings and original wooden pews give the venue an almost sacred feel — perfectly suited for the challenging, beautiful music they program. Experimental artists, ambient performers, and adventurous indie acts share the stage here. No talking during sets is not just requested, it's enforced.",
    coverCharge: 18,
    ageRestriction: "All Ages",
    capacity: 150,
    hours: "Wed–Sun 7pm–11pm",
    bestNight: "Wednesday",
    vibe: "Reverent & Adventurous",
    upcomingShows: [
      { date: "Wed Jun 11", artist: "Fern & the Understory", price: 15 },
      { date: "Fri Jun 13", artist: "Pale Signal (experimental)", price: 18 },
      { date: "Sat Jun 14", artist: "Cassette Choir", price: 20 },
      { date: "Sun Jun 15", artist: "Sunday Ambient Evening", price: 12 },
    ],
  },
];

function getVenueBySlug(slug) {
  return venues.find((v) => v.slug === slug) || null;
}

module.exports = { venues, getVenueBySlug };
